<?php

/**
 * Implements hook_node_info() to provide our nemac_mailing_list type.
 */
function nemac_mailing_list_node_info() {
  return array(
    'nemac_mailing_list' => array(
      'name'        => t('NEMAC Mailing List'),
      'base'        => 'nemac_mailing_list',
      'description' => t('A mailing list in the @nemac.org domain'),
      'has_title'   => TRUE,
      'title_label' => t('List Address'),
      'help'        => t('Enter the details for a NEMAC Mailing List here, bozo!'),
    ),
  );
}

/**
 * Implementation of hook_permission().
 */
function nemac_mailing_list_permission() { 
  return array(
  'create NEMAC Mailing List' => array(
    'title' => t('Create a NEMAC Mailing List'),
    'description' => t('Create a NEMAC Mailing List'),
  ),
  'edit own NEMAC Mailing List' => array(
    'title' => t('Edit own NEMAC Mailing List'),
    'description' => t('Edit your own NEMAC Mailing List'),
  ),
  'edit any NEMAC Mailing List' => array(
    'title' => t('Edit any NEMAC Mailing List'),
    'description' => t('Edit any NEMAC Mailing List'),
  ),
  'delete own NEMAC Mailing List' => array(
    'title' => t('Delete own NEMAC Mailing List'),
    'description' => t('Delete own NEMAC Mailing List'),
  ),
  'delete any NEMAC Mailing List' => array(
    'title' => t('Delete any NEMAC Mailing List'),
    'description' => t('Delete any NEMAC Mailing List'),
  ),
 );
}


/**
 * Implement hook_form() with the standard default form.
 */
function nemac_mailing_list_form($node, $form_state) {
  $form = node_content_form($node, $form_state);
  return $form;
}


/*
 * return an array of the email addresses for a nemac_mailing_list node
 */
function nemac_mailing_list_addresses($node) {
  // initialize array to store list addresses
  $addrs = array();

  // load addresses of (active) users in the selected roles
  //   assemble the rids of the selected roles into $rids array:
  $rids = array();
  $include_all_authenticated_users = False;
  if ($node->field_nemac_mailing_list_roles) {
    foreach ($node->field_nemac_mailing_list_roles['und'] as $ridarray) {
      $rid = $ridarray['value'];
      $role = user_role_load($rid);
      if ($role->name == 'authenticated user') {
	$include_all_authenticated_users = True;
      }
      $rids[] = $rid;
    }
    //   load the addresses of any (active) users in those roles into the $addrs array:
    $query = db_select('users_roles', 'ur')
      ->fields('ur', array('uid'));
    if (!$include_all_authenticated_users) {
      $query = $query->condition('rid', $rids, 'in');
    }
    $result2 = $query->execute();
    while ($record2 = $result2->fetchAssoc()) {
      $user = user_load($record2['uid']);
      $addrs[] = $user->mail;
    }
  }

  // load addresses of specifically listed users:
  if ($node->field_nemac_mailing_list_users) {
    foreach ($node->field_nemac_mailing_list_users['und'] as $uid) {
      $user = user_load($uid['target_id']);
      $addrs[] = $user->mail;
    }
  }

  // load specifically listed addresses:
  if ($node->field_nemac_mailing_list_addrs) {
    foreach (preg_split('/[\s,]+/', $node->field_nemac_mailing_list_addrs['und']['0']['value'])
	     as $addr) {
      if ($addr) {
	$addrs[] = $addr;
      }
    }
  }

  return $addrs;
}


/**
 * Implement hook_view().
 */
function nemac_mailing_list_view($node, $view_mode) { 
  if ($view_mode == 'full') {
    $addresses  = nemac_mailing_list_addresses($node);
    $node->content['addresses'] = array(
      '#markup' => theme('nemac_mailing_list_addresses',
			 array('addresses' => $addresses)),
      '#weight' => 10,
    );
  }
  return $node; 
}

 
/**
 * Implementation of hook_theme().
 */
function nemac_mailing_list_theme() {
  return array(
    'nemac_mailing_list_addresses' => array('variables' => array('addresses' => NULL),
					    'template'  => 'nemac_mailing_list_addresses'),
					    
	       );
}
